version: "3.9"

services:
  app:
    build:
      context: .
    container_name: beer_wiki_app
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/my_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 4ekhl1DpLe
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    extra_hosts:
      - "host.docker.internal:host-gateway"