services:
  app:
    build:
      context: .
    container_name: beer_wiki_app
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/beer_service
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 4ekhl1DpLe
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    networks:
      - mynetwork

  db:
    image: postgres:16
    container_name: beer_wiki_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 4ekhl1DpLe
      POSTGRES_DB: beer_service
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  mynetwork:

volumes:
  db_data: